name: "ci"

on:
  push:
    branches: [main]
    workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@/2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17'

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: PanZhangOne/web-picture-view@v2
        with:
          target_branch: gh-pages
          build_dir: ./dist
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

